on:
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'scalaz' }}
    timeout-minutes: 10
    steps:
    - name: Generate token
      id: generate_token
      uses: tibdex/github-app-token@v2
      with:
        app_id: 89659
        private_key: ${{ secrets.SCALAZ_BOT_KEY }}
    - uses: actions/checkout@v4
      with:
        token: ${{ steps.generate_token.outputs.token }}
